---
services:
  - type: web
    name: du-backend
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: du-postgres
          property: connectionString
      - key: APP_ENV
        value: production
      - key: ALLOWED_ORIGINS
        value: "*"
      - key: STORAGE_DRIVER
        value: s3
      - key: S3_ENDPOINT
        value: ""
      - key: S3_REGION
        value: "ap-southeast-1"
      - key: S3_BUCKET
        value: ""
      - key: S3_ACCESS_KEY
        value: ""
      - key: S3_SECRET_KEY
        value: ""
      - key: STORAGE_BASE_URL
        value: ""
      - key: STORAGE_DISK_PATH
        value: "/data/uploads"
    disk:
      name: uploads
      mountPath: /data
      sizeGB: 1
    dockerCommand: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "10000"]
databases:
  - name: du-postgres
    plan: free
